name: Daily Tweet Classifier

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  classify-tweets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove unused sys import
        run: |
          # delete any line that says "import sys"
          sed -i '/import sys/d' main.py

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome, Chromedriver & Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            chromium-chromedriver \
            xvfb
          chromedriver --version || echo "Chromedriver installation failed"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories
        run: |
          mkdir -p data
          mkdir -p debug_screenshots

      - name: Debug Secrets
        env:
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        run: |
          echo "TWITTER_USERNAME is set: ${TWITTER_USERNAME:-not set}"
          echo "TWITTER_PASSWORD is set: ${TWITTER_PASSWORD:-not set}"

      - name: Run Tweet Classifier
        env:
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        run: |
          export SCRIPT_TIMEOUT=600
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1200x24' \
            python main.py
          echo "Directory contents after script:"
          ls -la data/ || echo "data directory not found or empty"
          ls -la debug_screenshots/ || echo "screenshots directory not found"

      - name: Commit and push JSON files
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data/tweets_with_bias_*.json'
          message: 'chore: update tweets classification data'
          default_author: github_actions

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            debug_screenshots/
            data/
