name: Daily Tweet Classifier

# Trigger at 14:00 UTC (10:00 AM EDT during DST, 10:00 AM EST otherwise) daily, and allow manual runs
# Note: 14:00 UTC aligns with 10:00 AM EDT (DST) or 10:00 AM EST (standard time)
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

permissions:
  contents: write   # allow committing back to the repo

jobs:
  classify-tweets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Verify Chromedriver installation
          chromedriver --version || echo "Chromedriver installation failed"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Tweet Classifier
        env:
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        run: |
          python main.py
          # Display directory contents for debugging
          ls -la data/ || echo "data directory not found or empty"

      - name: Commit and push JSON file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data/tweets_with_bias_*.json'  # Keep this pattern
          message: 'chore: update tweets classification data'
          default_author: github_actions
