name: Daily Tweet Classifier

on:
  schedule:
    - cron: '0 14 * * *'      # 14:00 UTC = 10:00 AM EDT daily
  workflow_dispatch:          # manual trigger support

jobs:
  classify-tweets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tweet Classifier
        env:
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        run: |
          python twitter_scraper_with_bias.py

      - name: Commit and push results
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data/tweets_with_bias.json'
          message: 'chore: update tweets_with_bias.json'
          default_author: github_actions
