name: Daily Tweet Classifier

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  classify-tweets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          chromedriver --version || echo "Chromedriver installation failed"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Create directories
        run: |
          mkdir -p data
          mkdir -p debug_screenshots

      - name: Run Tweet Classifier
        env:
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        run: |
          # Increase timeout for slow environments
          export SCRIPT_TIMEOUT=600
          python main.py
          ls -la data/
          ls -la debug_screenshots/ || echo "No debug screenshots"

      - name: Commit and push JSON files
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data/tweets_with_bias_*.json'
          message: 'chore: update tweets classification data'
          default_author: github_actions

      - name: Upload debug screenshots
        if: failure()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: debug-screenshots
          path: debug_screenshots/
